import { randomUUID } from "node:crypto";
import { NextResponse } from "next/server";
import { z } from "zod";
import { AuthError, authErrorResponse, requireAccount } from "@/lib/auth/session";
import { defaultPortfolioProfile, targetsAreValid, type PortfolioMethodProfile } from "@/lib/portfolio/alfatec-portfolio-method";
import { readCoreState, writeCoreState } from "@/lib/server/core-state";
import { assertSameOrigin, requestErrorResponse } from "@/lib/server/request-security";

export const runtime = "nodejs";
const targetSchema = z.object({ id: z.enum(["reserva_caixa", "renda_fixa", "acoes_brasileiras", "fiis", "etfs_brasileiros", "exterior", "criptomoedas", "outros"]), label: z.string().min(1).max(80), targetPercent: z.number().min(0).max(100), tolerancePp: z.number().min(0).max(50) }).strict();
const answersSchema = z.object({ objective: z.string().max(80), horizon: z.string().max(40), lossTolerance: z.string().max(40), liquidityNeed: z.string().max(40), experience: z.string().max(40), incomeGoal: z.string().max(80), contributionFrequency: z.string().max(40), averageContribution: z.number().min(0).max(100000000), emergencyReserve: z.string().max(40), restrictions: z.array(z.string().max(80)).max(30), monthlyExpenses: z.number().min(0).max(100000000), emergencyMonths: z.number().int().min(0).max(60), emergencyCurrentValue: z.number().min(0).max(1000000000) }).strict();
const profileSchema = z.object({ version: z.string().max(20), profileName: z.enum(["Conservador", "Moderado", "Balanceado", "Arrojado", "Agressivo", "Personalizado"]), answers: answersSchema, targets: z.array(targetSchema).length(8), reviewFrequency: z.enum(["mensal", "trimestral", "semestral", "anual"]), rebalancingMode: z.enum(["aportes_rendimentos", "somente_aportes", "completo_simulado"]) }).strict();
function isProfile(value: unknown): value is PortfolioMethodProfile { return Boolean(value && typeof value === "object" && typeof (value as PortfolioMethodProfile).userId === "string"); }

export async function GET(request: Request) { try { const account = await requireAccount(request); const state = await readCoreState(); const profile = (Array.isArray(state.portfolioProfiles) ? state.portfolioProfiles : []).filter(isProfile).find((item) => item.userId === account.id) ?? defaultPortfolioProfile(account.id); return NextResponse.json({ profile }, { headers: { "Cache-Control": "private, no-store" } }); } catch (error) { return authErrorResponse(error); } }
export async function PUT(request: Request) { try { assertSameOrigin(request); const account = await requireAccount(request); const parsed = profileSchema.safeParse(await request.json().catch(() => null)); if (!parsed.success) return NextResponse.json({ error: "Dados do perfil inválidos." }, { status: 422 }); if (!targetsAreValid(parsed.data.targets)) return NextResponse.json({ error: "A carteira-alvo deve totalizar exatamente 100%." }, { status: 422 }); const state = await readCoreState(); const profiles = (Array.isArray(state.portfolioProfiles) ? state.portfolioProfiles : []).filter(isProfile); const now = new Date().toISOString(); const previous = profiles.find((item) => item.userId === account.id); const profile: PortfolioMethodProfile = { ...parsed.data, userId: account.id, updatedAt: now, history: previous?.history ?? [] }; state.portfolioProfiles = [profile, ...profiles.filter((item) => item.userId !== account.id)]; state.auditLogs = [{ id: randomUUID(), action: "perfil_alfatec_carteira_atualizado", userId: account.id, userName: account.name, details: `Perfil ${profile.profileName} e carteira-alvo atualizados.`, createdAt: now, risk: "baixo" }, ...(state.auditLogs || [])]; await writeCoreState(state); return NextResponse.json({ profile }, { headers: { "Cache-Control": "private, no-store" } }); } catch (error) { if (error instanceof AuthError) return authErrorResponse(error); return requestErrorResponse(error); } }
