import { describe, expect, it } from "vitest";
import { analyzeAlfatecPortfolio, defaultPortfolioProfile, derivePortfolioProfile, simulateContribution, targetTotal, targetsAreValid } from "./alfatec-portfolio-method";
import type { PortfolioLine } from "@/lib/types";
function line(ticker: string, type: "ACAO" | "FII" | "ETF" | "BDR" | "CRIPTO", value: number, risk: "Baixo" | "Médio" | "Alto" = "Médio"): PortfolioLine { return { id: ticker, ticker, quantity: "1", averagePrice: String(value), assetType: type, broker: "Teste", purchaseDate: "2026-01-01", invested: value, currentValue: value, profit: 0, profitability: 0, estimatedDividendsYear: value * .08, estimatedDividendsMonth: value * .08 / 12, weight: 0, asset: { ticker, name: ticker, type, market: "B3", sector: "Setor", segment: "Segmento", currency: "BRL", price: value, changeDay: 0, changeMonth: 0, changeYear: 0, liquidity: 2_000_000, metrics: {}, priceHistory: [], score: 80, risk, tags: [], summary: "", updatedAt: new Date().toISOString(), source: "external" } }; }
describe("Método AlfaTec Carteira", () => {
  it("cria metas válidas totalizando 100%", () => { const profile = defaultPortfolioProfile("u1"); expect(targetTotal(profile.targets)).toBe(100); expect(targetsAreValid(profile.targets)).toBe(true); });
  it("recusa meta diferente de 100%", () => { const profile = defaultPortfolioProfile("u1"); profile.targets[0].targetPercent += 1; expect(targetsAreValid(profile.targets)).toBe(false); });
  it("classifica perfil pelo conjunto das respostas", () => { const profile = defaultPortfolioProfile("u1"); expect(derivePortfolioProfile({ ...profile.answers, lossTolerance: "muito_alta", horizon: "mais_10", experience: "avancado", liquidityNeed: "longo_prazo", emergencyReserve: "completa" })).toBe("Agressivo"); });
  it("não retorna score para carteira vazia", () => { const result = analyzeAlfatecPortfolio([], defaultPortfolioProfile("u1")); expect(result.score).toBeNull(); expect(result.confidence).toBe("Insuficiente"); });
  it("calcula concentração elevada para um único ativo", () => { const result = analyzeAlfatecPortfolio([line("PETR4", "ACAO", 10000)], defaultPortfolioProfile("u1")); expect(result.concentrationIndex).toBe(1); expect(result.largestPositionPercent).toBe(100); expect(result.attentionPoints.some((item) => item.includes("100.0%"))).toBe(true); });
  it("calcula desvios em pontos percentuais e reais", () => { const result = analyzeAlfatecPortfolio([line("PETR4", "ACAO", 6000), line("HGLG11", "FII", 4000)], defaultPortfolioProfile("u1")); const stocks = result.allocations.find((item) => item.id === "acoes_brasileiras")!; expect(stocks.currentPercent).toBe(60); expect(stocks.driftPp).toBe(35); expect(stocks.adjustmentValue).toBe(-3500); });
  it("distribui aporte apenas entre classes com déficit", () => { const analysis = analyzeAlfatecPortfolio([line("PETR4", "ACAO", 10000)], defaultPortfolioProfile("u1")); const suggestions = simulateContribution(analysis, 1000, "proporcional"); expect(suggestions.length).toBeGreaterThan(0); expect(suggestions.every((item) => item.classId !== "acoes_brasileiras")).toBe(true); expect(suggestions.reduce((sum, item) => sum + item.amount, 0)).toBeCloseTo(1000, 2); });
  it("prioriza o maior desequilíbrio", () => { const analysis = analyzeAlfatecPortfolio([line("PETR4", "ACAO", 10000)], defaultPortfolioProfile("u1")); const suggestions = simulateContribution(analysis, 500, "maior_desvio"); expect(suggestions[0].label).toBe("Renda fixa"); expect(suggestions[0].amount).toBe(500); });
});
