"use client";
import { useCallback, useEffect, useMemo, useState } from "react";
import { CheckCircle2, Clipboard, CreditCard, ExternalLink, FileText, Loader2, QrCode, RefreshCw, XCircle } from "lucide-react";

type Plan = { id: string; name: string; value: number; durationDays: number; status: string; permissions: string[] };
type Payment = { id: string; planId: string; method: string; amountInCents: number; originalAmountInCents: number; discountInCents: number; status: string; pixQrCodeBase64?: string | null; pixCopyPaste?: string | null; pixExpiresAt?: string | null; cardBrand?: string | null; cardLastFour?: string | null; paidAt?: string | null; createdAt: string; checkoutUrl?: string };
type Subscription = { id: string; planName: string; planPriceInCents: number; paymentMethod: string; status: string; expiresAt?: string | null; nextBillingAt?: string | null; autoRenew: boolean; cardBrand?: string | null; cardLastFour?: string | null };
type Billing = { config: { configured: boolean; databaseConfigured: boolean; providerConfigured: boolean; webhookConfigured: boolean; environment: "sandbox" | "production"; pixDiscountPercent: number; cardInstallments: number; annualInstallmentsEnabled: boolean }; payments: Payment[]; subscription: Subscription | null };
const brl=(cents:number)=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(cents/100);
const statusLabel:Record<string,string>={pending:"Aguardando pagamento",processing:"Em processamento",paid:"Pago",failed:"Falha na confirmacao",expired:"Expirado",cancelled:"Cancelado",refunded:"Estornado",chargeback:"Chargeback",active:"Ativa",past_due:"Pagamento atrasado"};

export function ClientPaymentCheckout({plans,currentPlanId}:{plans:Plan[];currentPlanId?:string}){
 const activePlans=useMemo(()=>plans.filter(plan=>plan.status==="ativo"),[plans]);
 const [billing,setBilling]=useState<Billing|null>(null);const [planId,setPlanId]=useState(currentPlanId||activePlans[1]?.id||activePlans[0]?.id||"");const [method,setMethod]=useState<"pix"|"credit_card">("pix");const [autoRenew,setAutoRenew]=useState(false);const [renewalMode,setRenewalMode]=useState<"extend"|"today">("extend");const [pending,setPending]=useState(false);const [error,setError]=useState("");const [checkout,setCheckout]=useState<Payment|null>(null);
 const load=useCallback(async()=>{const response=await fetch("/api/account/payments",{cache:"no-store"});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||"Nao foi possivel carregar os pagamentos.");setBilling(data);return data as Billing;},[]);
 useEffect(()=>{void load().catch(error=>setError(error.message));},[load]);
 const selected=activePlans.find(plan=>plan.id===planId);
 const originalCents=selected?Math.round(selected.value*100):0;const discountCents=method==="pix"?Math.round(originalCents*(billing?.config.pixDiscountPercent||0)/100):0;const estimatedTotal=originalCents-discountCents;
 useEffect(()=>{if(!checkout||!["pending","processing"].includes(checkout.status))return;const timer=window.setInterval(async()=>{const response=await fetch(`/api/payments/${checkout.id}/status`,{cache:"no-store"});if(response.ok){const data=await response.json();setCheckout(data);void load();}},10000);return()=>window.clearInterval(timer);},[checkout?.id,checkout?.status,load]);
 async function create(){setPending(true);setError("");try{const response=await fetch("/api/payments/checkout",{method:"POST",headers:{"Content-Type":"application/json","Idempotency-Key":crypto.randomUUID()},body:JSON.stringify({planId,paymentMethod:method,autoRenew:method==="credit_card"&&autoRenew,renewalMode})});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||"Nao foi possivel criar a cobranca.");setCheckout(data);await load();if(data.checkoutUrl)window.location.assign(data.checkoutUrl);}catch(error){setError(error instanceof Error?error.message:"Nao foi possivel criar a cobranca.");}finally{setPending(false);}}
 async function verify(id:string){setPending(true);setError("");try{const response=await fetch(`/api/payments/${id}/status`,{cache:"no-store"});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||"Nao foi possivel verificar.");setCheckout(data);await load();}catch(error){setError(error instanceof Error?error.message:"Falha ao verificar pagamento.");}finally{setPending(false);}}
 async function cancelSubscription(){if(!billing?.subscription)return;setPending(true);try{const response=await fetch(`/api/subscriptions/${billing.subscription.id}/cancel`,{method:"POST"});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||"Nao foi possivel cancelar a renovacao.");await load();}catch(error){setError(error instanceof Error?error.message:"Falha ao cancelar renovacao.");}finally{setPending(false);}}
 const pix=checkout?.method==="pix"?checkout:null;
 return <div className="space-y-5">
  {billing?.config.environment==="sandbox"&&<div className="rounded-2xl border border-amber-400/40 bg-amber-500/10 p-4 text-sm font-black text-amber-700 dark:text-amber-300">AMBIENTE DE TESTE - NENHUMA COBRANCA REAL</div>}
  {billing&&!billing.config.configured&&<div className="rounded-2xl border border-amber-400/40 bg-amber-500/10 p-4 text-sm text-amber-800 dark:text-amber-200"><strong>Pagamentos online ainda nao configurados.</strong><p className="mt-1">O administrador deve configurar DATABASE_URL, MERCADO_PAGO_ACCESS_TOKEN, MERCADO_PAGO_WEBHOOK_SECRET e PAYMENT_APP_URL na Vercel.</p></div>}
  <div className="grid gap-3 md:grid-cols-3">{activePlans.map(plan=><button key={plan.id} type="button" onClick={()=>setPlanId(plan.id)} className={`rounded-2xl border p-4 text-left ${planId===plan.id?"border-cyan-500 bg-cyan-500/10":"border-slate-200 dark:border-white/10"}`}><strong className="block">{plan.name}</strong><span className="mt-1 block text-xl font-black">{brl(Math.round(plan.value*100))}</span><small>{plan.durationDays} dias</small></button>)}</div>
  <div className="grid gap-3 sm:grid-cols-2"><button type="button" onClick={()=>{setMethod("pix");setAutoRenew(false);}} className={`flex items-center gap-3 rounded-2xl border p-4 font-bold ${method==="pix"?"border-cyan-500 bg-cyan-500/10":"border-slate-200 dark:border-white/10"}`}><QrCode/>Pix <span className="ml-auto text-xs text-emerald-600 dark:text-emerald-300">Melhor preco</span></button><button type="button" onClick={()=>setMethod("credit_card")} className={`flex items-center gap-3 rounded-2xl border p-4 font-bold ${method==="credit_card"?"border-cyan-500 bg-cyan-500/10":"border-slate-200 dark:border-white/10"}`}><CreditCard/>Cartao <span className="ml-auto text-xs text-cyan-600 dark:text-cyan-300">Maior conveniencia</span></button></div>
  {method==="credit_card"&&selected?.id!=="semanal"&&<label className="flex items-start gap-3 rounded-2xl bg-slate-50 p-4 text-sm dark:bg-white/5"><input type="checkbox" checked={autoRenew} onChange={event=>setAutoRenew(event.target.checked)} className="mt-1"/><span><strong>Renovacao automatica</strong><br/>Esta assinatura sera renovada automaticamente ate o cancelamento.</span></label>}
  <label className="block text-sm font-bold">Regra de renovacao<select value={renewalMode} onChange={event=>setRenewalMode(event.target.value as "extend"|"today")} className="mt-2 h-12 w-full rounded-2xl border border-slate-200 bg-white px-4 text-slate-950 dark:border-white/10 dark:bg-[#0f172a] dark:text-white"><option value="extend">Acrescentar ao vencimento atual</option><option value="today">Iniciar na confirmacao</option></select></label>
  <div className="rounded-2xl bg-slate-50 p-4 text-sm dark:bg-white/5"><p className="flex justify-between"><span>Plano</span><strong>{selected?.name||"-"}</strong></p><p className="mt-2 flex justify-between"><span>Valor oficial</span><strong>{selected?brl(originalCents):"-"}</strong></p>{method==="pix"&&discountCents>0&&<p className="mt-2 flex justify-between text-emerald-600 dark:text-emerald-300"><span>Desconto Pix</span><strong>- {brl(discountCents)}</strong></p>}<p className="mt-2 flex justify-between border-t border-slate-200 pt-2 dark:border-white/10"><span>Total estimado</span><strong>{selected?brl(estimatedTotal):"-"}</strong></p>{method==="credit_card"&&selected?.id==="anual"&&billing?.config.annualInstallmentsEnabled&&<p className="mt-2 text-xs font-semibold text-cyan-700 dark:text-cyan-300">Pagamento anual com parcelamento de ate {billing.config.cardInstallments} vezes, sujeito as regras do gateway.</p>}<p className="mt-2 text-xs text-slate-500 dark:text-slate-400">O valor final e os descontos sao recalculados pelo servidor a partir do banco de dados.</p></div>
  {error&&<div className="rounded-2xl bg-red-500/10 p-4 text-sm font-bold text-red-600 dark:text-red-300">{error}</div>}
  <button type="button" disabled={pending||!billing?.config.configured||!selected} onClick={create} className="flex w-full items-center justify-center gap-2 rounded-2xl bg-gradient-to-r from-cyan-500 to-blue-600 px-5 py-3 font-black text-white disabled:opacity-50">{pending?<Loader2 className="animate-spin"/>:method==="pix"?<QrCode/>:<ExternalLink/>}Confirmar pagamento</button>
  {pix&&<div className="rounded-3xl border border-cyan-400/30 bg-cyan-500/5 p-5"><h4 className="font-black">Pix - {statusLabel[pix.status]||pix.status}</h4><div className="mt-4 grid gap-4 md:grid-cols-[220px_1fr]">{pix.pixQrCodeBase64?<img src={pix.pixQrCodeBase64.startsWith("data:")?pix.pixQrCodeBase64:`data:image/png;base64,${pix.pixQrCodeBase64}`} alt="QR Code Pix desta cobranca" className="aspect-square w-full rounded-2xl bg-white p-3"/>:<div className="grid aspect-square place-items-center rounded-2xl bg-white text-slate-500"><QrCode className="h-16 w-16"/></div>}<div><p className="text-sm">Valor: <strong>{brl(pix.amountInCents)}</strong></p><p className="mt-2 text-sm">Validade: <strong>{pix.pixExpiresAt?new Date(pix.pixExpiresAt).toLocaleString("pt-BR"):"informada pelo provedor"}</strong></p>{pix.pixExpiresAt&&<PixCountdown expiresAt={pix.pixExpiresAt}/>}{pix.pixCopyPaste&&<><textarea readOnly value={pix.pixCopyPaste} className="mt-3 h-24 w-full rounded-2xl border border-slate-200 bg-white p-3 text-xs text-slate-950 dark:border-white/10 dark:bg-[#0f172a] dark:text-white"/><button type="button" onClick={()=>navigator.clipboard.writeText(pix.pixCopyPaste||"")} className="mt-2 flex items-center gap-2 rounded-xl bg-slate-950 px-4 py-2 text-sm font-bold text-white dark:bg-white dark:text-slate-950"><Clipboard className="h-4 w-4"/>Copiar codigo</button></>}<button type="button" onClick={()=>verify(pix.id)} className="mt-3 flex items-center gap-2 rounded-xl bg-cyan-500 px-4 py-2 text-sm font-bold text-white"><RefreshCw className="h-4 w-4"/>Verificar pagamento</button></div></div><p className="mt-4 text-xs text-slate-500 dark:text-slate-400">O plano so sera liberado apos confirmacao valida do Mercado Pago.</p></div>}
  {billing?.subscription&&<div className="rounded-3xl border border-slate-200 p-5 dark:border-white/10"><h4 className="font-black">Assinatura online</h4><div className="mt-3 grid gap-2 text-sm sm:grid-cols-2"><span>Plano: <strong>{billing.subscription.planName}</strong></span><span>Status: <strong>{statusLabel[billing.subscription.status]||billing.subscription.status}</strong></span><span>Metodo: <strong>{billing.subscription.paymentMethod==="pix"?"Pix":`${billing.subscription.cardBrand||"Cartao"} ???? ${billing.subscription.cardLastFour||"----"}`}</strong></span><span>Proxima cobranca: <strong>{billing.subscription.nextBillingAt?new Date(billing.subscription.nextBillingAt).toLocaleDateString("pt-BR"):"-"}</strong></span></div>{billing.subscription.autoRenew&&<button type="button" onClick={cancelSubscription} className="mt-4 flex items-center gap-2 rounded-xl bg-red-500/10 px-4 py-2 text-sm font-bold text-red-600 dark:text-red-300"><XCircle className="h-4 w-4"/>Cancelar renovacao automatica</button>}</div>}
  <div><h4 className="font-black">Ultimos pagamentos</h4><div className="mt-3 space-y-2">{billing?.payments.map(payment=><div key={payment.id} className="grid gap-2 rounded-2xl bg-slate-50 p-3 text-sm dark:bg-white/5 sm:grid-cols-[1fr_auto_auto]"><span><strong>{plans.find(plan=>plan.id===payment.planId)?.name||payment.planId}</strong><small className="block text-slate-500 dark:text-slate-400">{new Date(payment.createdAt).toLocaleString("pt-BR")} ? {payment.method==="pix"?"Pix":"Cartao"}</small></span><span className="font-bold">{brl(payment.amountInCents)}</span><span className="flex items-center gap-2">{payment.status==="paid"?<CheckCircle2 className="h-4 w-4 text-emerald-500"/>:<RefreshCw className="h-4 w-4 text-amber-500"/>}{statusLabel[payment.status]||payment.status}{payment.status==="paid"&&<a href={`/api/payments/${payment.id}/receipt`} target="_blank" rel="noreferrer" title="Abrir recibo" className="rounded-lg p-1 hover:bg-slate-200 dark:hover:bg-white/10"><FileText className="h-4 w-4"/></a>}</span></div>)}{billing?.payments.length===0&&<p className="text-sm text-slate-500 dark:text-slate-400">Nenhum pagamento online registrado.</p>}</div></div>
 </div>;
}

function PixCountdown({expiresAt}:{expiresAt:string}){const [remaining,setRemaining]=useState(0);useEffect(()=>{const tick=()=>setRemaining(Math.max(0,new Date(expiresAt).getTime()-Date.now()));tick();const timer=window.setInterval(tick,1000);return()=>window.clearInterval(timer);},[expiresAt]);const minutes=Math.floor(remaining/60000);const seconds=Math.floor((remaining%60000)/1000);return <p className="mt-2 text-sm">Tempo restante: <strong>{remaining>0?`${minutes}:${String(seconds).padStart(2,"0")}`:"Expirado"}</strong></p>;}
