export type ReportSectionOption = {
  id: string;
  label: string;
  group: string;
  description: string;
};

export const clientReportSections: ReportSectionOption[] = [
  { id: "summary", label: "Resumo da carteira", group: "Carteira", description: "Indicadores executivos da carteira." },
  { id: "account-plan", label: "Plano e assinatura", group: "Conta", description: "Plano, valor, status e vencimento." },
  { id: "payment-history", label: "Histórico de pagamentos", group: "Conta", description: "Pagamentos registrados para a conta." },
  { id: "equity", label: "Patrimônio", group: "Carteira", description: "Capital investido e patrimônio atual." },
  { id: "returns", label: "Rentabilidade", group: "Carteira", description: "Rentabilidade consolidada e por ativo." },
  { id: "profit-loss", label: "Lucro e prejuízo", group: "Carteira", description: "Resultados financeiros por posição." },
  { id: "dividends", label: "Dividendos", group: "Carteira", description: "Projeções com base nos indicadores disponíveis." },
  { id: "allocation-class", label: "Distribuição por classe", group: "Distribuição", description: "Participação por tipo de ativo." },
  { id: "allocation-sector", label: "Distribuição por setor", group: "Distribuição", description: "Participação por setor." },
  { id: "assets", label: "Ativos da carteira", group: "Carteira", description: "Posições, preços e pesos." },
  { id: "movements", label: "Histórico de movimentações", group: "Histórico", description: "Entradas registradas na carteira." },
  { id: "benchmark", label: "Benchmark", group: "Análises", description: "Comparação com referência, quando disponível." },
  { id: "opportunities", label: "Oportunidades", group: "Análises", description: "Ativos analisados pelos métodos da plataforma." },
  { id: "risks", label: "Riscos", group: "Análises", description: "Alertas e concentrações identificadas." },
  { id: "rebalancing", label: "Sugestões de rebalanceamento", group: "Análises", description: "Leituras automatizadas da carteira." },
  { id: "graham", label: "Método Graham", group: "Métodos", description: "Número de Graham para ativos aplicáveis." },
  { id: "fii", label: "Método AlfaTec FIIs", group: "Métodos", description: "Scores reais dos fundos analisados." },
  { id: "crypto", label: "Método AlfaTec Cripto", group: "Métodos", description: "Scores reais dos criptoativos analisados." },
  { id: "score-history", label: "Histórico dos scores", group: "Histórico", description: "Evolução registrada dos scores." },
  { id: "alerts", label: "Alertas", group: "Análises", description: "Alertas ativos da carteira." },
  { id: "charts", label: "Gráficos", group: "Distribuição", description: "Gráficos de classe e setor." }
];

export const adminReportSections: ReportSectionOption[] = [
  { id: "clients-list", label: "Lista de clientes", group: "Relatórios de clientes", description: "Relação de clientes cadastrados." },
  { id: "clients-active", label: "Clientes ativos", group: "Relatórios de clientes", description: "Clientes com acesso ativo." },
  { id: "clients-blocked", label: "Clientes bloqueados", group: "Relatórios de clientes", description: "Clientes bloqueados." },
  { id: "clients-pending", label: "Clientes pendentes", group: "Relatórios de clientes", description: "Cadastros aguardando liberação." },
  { id: "clients-new", label: "Novos clientes", group: "Relatórios de clientes", description: "Cadastros no período selecionado." },
  { id: "clients-last-access", label: "Últimos acessos", group: "Relatórios de clientes", description: "Último acesso disponível no sistema." },
  { id: "clients-by-plan", label: "Clientes por plano", group: "Relatórios de clientes", description: "Distribuição dos clientes por plano." },
  { id: "clients-expiring", label: "Clientes próximos do vencimento", group: "Relatórios de clientes", description: "Vencimentos nos próximos sete dias." },
  { id: "clients-expired", label: "Clientes com plano vencido", group: "Relatórios de clientes", description: "Clientes com prazo encerrado." },
  { id: "finance-total", label: "Receita total", group: "Relatórios financeiros", description: "Receita confirmada no período." },
  { id: "finance-monthly", label: "Receita mensal", group: "Relatórios financeiros", description: "Receita agrupada por mês." },
  { id: "finance-annual", label: "Receita anual", group: "Relatórios financeiros", description: "Receita agrupada por ano." },
  { id: "payments-confirmed", label: "Pagamentos confirmados", group: "Relatórios financeiros", description: "Pagamentos com status pago." },
  { id: "payments-pending", label: "Pagamentos pendentes", group: "Relatórios financeiros", description: "Pagamentos aguardando confirmação." },
  { id: "subscriptions-review", label: "Solicitações em análise", group: "Relatórios financeiros", description: "Solicitações de assinatura em análise." },
  { id: "subscriptions-rejected", label: "Solicitações recusadas", group: "Relatórios financeiros", description: "Solicitações encerradas como recusadas." },
  { id: "subscriptions-active", label: "Assinaturas ativas", group: "Relatórios financeiros", description: "Assinaturas vigentes." },
  { id: "subscriptions-expired", label: "Assinaturas vencidas", group: "Relatórios financeiros", description: "Assinaturas vencidas." },
  { id: "renewals", label: "Renovações", group: "Relatórios financeiros", description: "Pagamentos registrados como renovação." },
  { id: "cancellations", label: "Cancelamentos", group: "Relatórios financeiros", description: "Pagamentos e assinaturas cancelados." },
  { id: "gross-values", label: "Valores brutos", group: "Relatórios financeiros", description: "Valores registrados antes de ajustes." },
  { id: "fees", label: "Taxas", group: "Relatórios financeiros", description: "Taxas informadas nos registros." },
  { id: "net-values", label: "Valores líquidos", group: "Relatórios financeiros", description: "Valores líquidos identificados." },
  { id: "plans", label: "Planos semanal, mensal e anual", group: "Relatórios de planos", description: "Valores, duração e status dos planos." },
  { id: "plan-weekly", label: "Plano semanal", group: "Relatórios de planos", description: "Valor, duração e status do plano semanal." },
  { id: "plan-monthly", label: "Plano mensal", group: "Relatórios de planos", description: "Valor, duração e status do plano mensal." },
  { id: "plan-annual", label: "Plano anual", group: "Relatórios de planos", description: "Valor, duração e status do plano anual." },
  { id: "plans-count", label: "Quantidade por plano", group: "Relatórios de planos", description: "Quantidade de clientes por plano." },
  { id: "plans-revenue", label: "Receita por plano", group: "Relatórios de planos", description: "Receita confirmada por plano." },
  { id: "renewal-rate", label: "Taxa de renovação", group: "Relatórios de planos", description: "Taxa calculada com registros disponíveis." },
  { id: "cancellation-rate", label: "Taxa de cancelamento", group: "Relatórios de planos", description: "Taxa calculada com registros disponíveis." },
  { id: "usage-active", label: "Usuários ativos", group: "Relatórios de uso", description: "Clientes com conta ativa." },
  { id: "usage-inactive", label: "Usuários inativos", group: "Relatórios de uso", description: "Clientes sem conta ativa." },
  { id: "usage-access", label: "Acessos", group: "Relatórios de uso", description: "Histórico de acessos, quando registrado." },
  { id: "usage-features", label: "Funcionalidades mais utilizadas", group: "Relatórios de uso", description: "Uso agregado por funcionalidade, quando registrado." },
  { id: "usage-reports", label: "Relatórios gerados", group: "Relatórios de uso", description: "Exportações registradas no período." },
  { id: "usage-assets", label: "Ativos mais pesquisados", group: "Relatórios de uso", description: "Pesquisas persistidas, quando disponíveis." },
  { id: "usage-ai", label: "Uso da AlfaTec IA", group: "Relatórios de uso", description: "Uso persistido da análise por IA, quando disponível." },
  { id: "system-health", label: "Saúde do sistema", group: "Relatórios do sistema", description: "Estado das integrações e armazenamento." },
  { id: "api-status", label: "Status das APIs", group: "Relatórios do sistema", description: "Estado persistido das integrações, quando disponível." },
  { id: "sync-failures", label: "Falhas de sincronização", group: "Relatórios do sistema", description: "Falhas persistidas de atualização." },
  { id: "stale-data", label: "Dados desatualizados", group: "Relatórios do sistema", description: "Indicadores de atraso persistidos." },
  { id: "email-history", label: "Histórico de e-mails", group: "Relatórios do sistema", description: "Entregas e falhas registradas." },
  { id: "notification-history", label: "Histórico de notificações", group: "Relatórios do sistema", description: "Notificações persistidas." },
  { id: "audit", label: "Logs de auditoria", group: "Relatórios do sistema", description: "Ações administrativas registradas." },
  { id: "backups", label: "Backups", group: "Relatórios do sistema", description: "Status de backup quando disponível." },
  { id: "errors", label: "Erros do sistema", group: "Relatórios do sistema", description: "Erros persistidos quando disponíveis." }
];
