import { randomUUID } from "node:crypto";
import { NextResponse } from "next/server";
import { z } from "zod";
import { hashPassword,passwordPolicy } from "@/lib/auth/password";
import { readCoreState,writeCoreState } from "@/lib/server/core-state";
import { assertSameOrigin } from "@/lib/server/request-security";
export const runtime="nodejs";
const schema=z.object({name:z.string().trim().min(2).max(120),email:z.string().trim().email().max(254),phone:z.string().trim().max(30).optional().default(""),password:z.string().min(1).max(256),planId:z.string().trim().min(1).max(50)}).strict();
export async function POST(request:Request){try{assertSameOrigin(request);const parsed=schema.safeParse(await request.json().catch(()=>null));if(!parsed.success)return NextResponse.json({error:"Revise os dados informados."},{status:422});const input=parsed.data;const email=input.email.toLowerCase();const policy=passwordPolicy(input.password,{name:input.name,email});if(policy)return NextResponse.json({error:policy},{status:422});const state=await readCoreState();if(state.accounts.some(item=>item.email.toLowerCase()===email||item.name.toLowerCase()===input.name.toLowerCase()))return NextResponse.json({error:"Ja existe uma conta com esse nome ou e-mail."},{status:409});const plan=state.plans.find(item=>item.id===input.planId&&item.status==="ativo");if(!plan)return NextResponse.json({error:"Plano indisponivel."},{status:422});const account={id:randomUUID(),role:"CLIENTE" as const,username:email,email,name:input.name,phone:input.phone,passwordHash:await hashPassword(input.password),planId:plan.id,planValue:plan.value,status:"pendente",createdAt:new Date().toISOString().slice(0,10),notes:"Cadastro solicitado pelo usuario. Aguardando liberacao do admin.",permissions:plan.permissions};state.accounts=[account,...state.accounts];state.auditLogs=[{id:randomUUID(),action:"cadastro_solicitado",userId:account.id,userName:account.name,details:"Nova conta aguardando aprovacao.",createdAt:new Date().toISOString(),risk:"baixo"},...(state.auditLogs||[])];await writeCoreState(state);return NextResponse.json({ok:true,message:"Conta criada. Aguarde a liberacao do administrador para acessar."},{status:201});}catch{return NextResponse.json({error:"Nao foi possivel criar a conta."},{status:500});}}
