import { AlertTriangle, Bitcoin, CheckCircle2 } from "lucide-react";
import type { AlfatecCryptoAnalysis } from "@/lib/analysis/alfatec-crypto";
import { CryptoConfidenceBadge } from "./CryptoConfidenceBadge";
export function AlfatecCryptoScoreCard({ analysis }: { analysis: AlfatecCryptoAnalysis }) {
  return <div className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm dark:border-white/10 dark:bg-slate-900">
    <div className="flex flex-wrap items-start justify-between gap-3"><div className="flex items-center gap-3"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-amber-500/10 text-amber-500"><Bitcoin className="h-6 w-6" /></span><div><p className="text-xs font-black uppercase tracking-[0.18em] text-cyan-600 dark:text-cyan-300">Metodo AlfaTec Cripto</p><h3 className="text-2xl font-black">{analysis.ticker} - {analysis.name}</h3><p className="text-sm text-slate-500 dark:text-slate-300">{analysis.categoryLabel}{analysis.secondaryCategory ? ` / ${analysis.secondaryCategory}` : ""}</p></div></div><CryptoConfidenceBadge value={analysis.confidence} /></div>
    <div className="mt-5 grid gap-3 sm:grid-cols-3"><div className="rounded-2xl bg-slate-950 p-4 text-white dark:bg-white/10"><p className="text-xs uppercase text-slate-300">Score AlfaTec Cripto</p><strong className="text-3xl">{analysis.score === null ? "--" : `${analysis.score}/100`}</strong></div><div className="rounded-2xl bg-slate-50 p-4 dark:bg-white/5"><p className="text-xs text-slate-500 dark:text-slate-300">Classificacao</p><strong>{analysis.classification}</strong></div><div className="rounded-2xl bg-slate-50 p-4 dark:bg-white/5"><p className="text-xs text-slate-500 dark:text-slate-300">Atualizacao</p><strong className="text-sm">{new Date(analysis.snapshot.updatedAt).toLocaleString("pt-BR")}</strong></div></div>
    {!analysis.applicable && <p className="mt-4 flex gap-2 rounded-2xl bg-amber-500/10 p-3 text-sm font-semibold text-amber-700 dark:text-amber-300"><AlertTriangle className="h-5 w-5 shrink-0" />Dados reais insuficientes para calcular o Score AlfaTec Cripto.</p>}
    <div className="mt-5 grid gap-4 md:grid-cols-2"><div><h4 className="flex items-center gap-2 font-black"><CheckCircle2 className="h-4 w-4 text-emerald-500" />Pontos positivos</h4><ul className="mt-2 space-y-2 text-sm text-slate-600 dark:text-slate-300">{analysis.positives.length ? analysis.positives.map((item) => <li key={item}>- {item}</li>) : <li>Dado indisponivel para destacar pontos positivos.</li>}</ul></div><div><h4 className="flex items-center gap-2 font-black"><AlertTriangle className="h-4 w-4 text-amber-500" />Pontos de atencao</h4><ul className="mt-2 space-y-2 text-sm text-slate-600 dark:text-slate-300">{[...analysis.attentionPoints, ...analysis.risks].map((item) => <li key={item}>- {item}</li>)}</ul></div></div>
  </div>;
}
