"use client";
import { AlertTriangle, Bitcoin, RefreshCw, Save, Search, Settings } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import type { Asset } from "@/lib/types";
import { compareCryptoByCategory, cryptoCategoryLabels, type AlfatecCryptoAnalysis, type CryptoCategory, type CryptoPillar, type CryptoSettings } from "@/lib/analysis/alfatec-crypto";
import { AlfatecCryptoScoreCard } from "./AlfatecCryptoScoreCard";
import { CryptoDataSourceInfo } from "./CryptoDataSourceInfo";
import { CryptoScoreBreakdown } from "./CryptoScoreBreakdown";

const money = new Intl.NumberFormat("pt-BR", { style: "currency", currency: "USD" });
const compact = new Intl.NumberFormat("pt-BR", { notation: "compact", maximumFractionDigits: 2 });
const pillarLabels: Record<CryptoPillar, string> = { fundamentals: "Fundamentos", network: "Rede", tokenomics: "Tokenomics", security: "Seguranca", market: "Mercado", development: "Desenvolvimento", onChainValuation: "Valuation on-chain", risk: "Risco" };
const card = "rounded-3xl border border-slate-200 bg-white p-5 dark:border-white/10 dark:bg-slate-900";

export function AlfatecCryptoSection({ assets, analyses, selectedTicker, loading, error, currentUserRole, settings, onSelect, onRefresh, onSaveSettings }: { assets: Asset[]; analyses: AlfatecCryptoAnalysis[]; selectedTicker: string; loading: boolean; error: string; currentUserRole: "ADMIN" | "CLIENTE"; settings: CryptoSettings; onSelect: (ticker: string) => void; onRefresh: (ticker: string) => void; onSaveSettings: (settings: CryptoSettings) => void }) {
  const [query, setQuery] = useState(selectedTicker);
  const selected = analyses.find((item) => item.ticker === selectedTicker) ?? null;
  const cryptoAssets = assets.filter((asset) => asset.type === "CRIPTO");
  const suggestions = useMemo(() => { const q = query.toLowerCase().trim(); return cryptoAssets.filter((asset) => !q || asset.ticker.toLowerCase().includes(q) || asset.name.toLowerCase().includes(q)).slice(0, 8); }, [cryptoAssets, query]);
  return <section className="space-y-6"><div><p className="text-xs font-black uppercase tracking-[0.2em] text-cyan-600 dark:text-cyan-300">Criptoativos</p><h2 className="text-3xl font-black">Metodo AlfaTec Cripto</h2><p className="mt-1 text-slate-500 dark:text-slate-300">Fundamentos, rede, tokenomics, seguranca, liquidez, desenvolvimento, valuation on-chain e risco.</p></div><div className="grid gap-6 xl:grid-cols-[0.8fr_1.2fr]"><div className="space-y-6"><div className={card}><div className="flex items-center justify-between gap-3"><div><h3 className="font-black">Pesquisar criptoativo</h3><p className="text-sm text-slate-500 dark:text-slate-300">Nome ou simbolo, com dados atuais da fonte.</p></div><Bitcoin className="h-6 w-6 text-amber-500" /></div><div className="relative mt-4"><Search className="absolute left-4 top-3.5 h-5 w-5 text-slate-400" /><input value={query} onChange={(e) => setQuery(e.target.value)} className="h-12 w-full rounded-2xl border border-slate-200 bg-white pl-12 pr-4 text-slate-950 outline-none dark:border-white/10 dark:bg-slate-950 dark:text-white" placeholder="Bitcoin, BTC, Ethereum..." />{query && <div className="absolute z-20 mt-2 w-full overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-xl dark:border-white/10 dark:bg-slate-950">{suggestions.map((asset) => <button key={asset.ticker} type="button" onClick={() => { setQuery(asset.ticker); onSelect(asset.ticker); }} className="flex w-full justify-between px-4 py-3 text-left text-sm hover:bg-slate-50 dark:hover:bg-white/5"><span><strong>{asset.ticker}</strong> <span className="text-slate-500 dark:text-slate-300">{asset.name}</span></span><span className="text-xs text-slate-400">{asset.segment}</span></button>)}</div>}</div><button type="button" onClick={() => onRefresh(selectedTicker)} disabled={loading} className="mt-4 inline-flex items-center gap-2 rounded-2xl bg-cyan-500 px-4 py-3 text-sm font-black text-white disabled:opacity-60"><RefreshCw className={`h-4 w-4 ${loading ? "animate-spin" : ""}`} />Atualizar dados</button>{error && <p className="mt-3 flex gap-2 rounded-2xl bg-red-500/10 p-3 text-sm font-semibold text-red-600 dark:text-red-300"><AlertTriangle className="h-5 w-5" />{error}</p>}</div><MethodExplanation />{currentUserRole === "ADMIN" && <CryptoAdminSettings settings={settings} selectedCategory={selected?.category ?? "other"} onSave={onSaveSettings} />}</div><div className="space-y-6">{selected ? <><AlfatecCryptoScoreCard analysis={selected} /><CryptoMarketSummary analysis={selected} /><CryptoScoreBreakdown analysis={selected} /><CryptoPeerSummary selected={selected} analyses={analyses} /><CryptoDataSourceInfo analysis={selected} /></> : <div className={card}><p className="text-sm text-slate-500">Selecione um criptoativo para carregar a analise real.</p></div>}</div></div></section>;
}

function CryptoMarketSummary({ analysis }: { analysis: AlfatecCryptoAnalysis }) { const s = analysis.snapshot; const risk = analysis.pillars.find((item) => item.key === "risk")?.score; return <div className={`${card} grid gap-3 sm:grid-cols-2 lg:grid-cols-4`}><Metric label="Preco atual" value={s.price === null ? "Dado indisponivel" : money.format(s.price)} /><Metric label="Variacao 24h" value={s.change24h === null ? "Dado indisponivel" : `${s.change24h.toFixed(2)}%`} /><Metric label="Capitalizacao" value={s.marketCap === null ? "Dado indisponivel" : `US$ ${compact.format(s.marketCap)}`} /><Metric label="Volume 24h" value={s.volume24h === null ? "Dado indisponivel" : `US$ ${compact.format(s.volume24h)}`} /><Metric label="Oferta circulante" value={s.circulatingSupply === null ? "Dado indisponivel" : compact.format(s.circulatingSupply)} /><Metric label="Oferta maxima" value={s.maxSupply === null ? "Sem limite informado" : compact.format(s.maxSupply)} /><Metric label="Distancia da maxima" value={s.athChangePercent === null ? "Dado indisponivel" : `${s.athChangePercent.toFixed(2)}%`} /><Metric label="Indice de risco" value={risk === null || risk === undefined ? "Dado indisponivel" : `${risk}/100`} /></div>; }
function Metric({ label, value }: { label: string; value: string }) { return <div className="rounded-2xl bg-slate-50 p-3 dark:bg-white/5"><p className="text-xs text-slate-500 dark:text-slate-300">{label}</p><strong>{value}</strong></div>; }
function MethodExplanation() { return <div className={card}><h3 className="font-black">Entenda o metodo</h3><div className="mt-3 space-y-3 text-sm text-slate-600 dark:text-slate-300"><p>O Metodo AlfaTec Cripto adapta os pesos a categoria do ativo e nao utiliza Graham, P/L, P/VP ou Dividend Yield. Dados ausentes nao viram zero e reduzem a confianca.</p><p>MVRV, NVT, TVL e atividade da rede so entram quando uma fonte compativel os fornece. Popularidade e alta recente nao geram nota alta sozinhas.</p><p className="rounded-2xl bg-amber-500/10 p-3 font-semibold text-amber-700 dark:text-amber-300">O Metodo AlfaTec Cripto e um modelo analitico proprio. A pontuacao nao representa garantia de valorizacao, rendimento ou recomendacao personalizada. Criptoativos podem causar perda parcial ou total do capital.</p></div></div>; }
function CryptoPeerSummary({ selected, analyses }: { selected: AlfatecCryptoAnalysis; analyses: AlfatecCryptoAnalysis[] }) { const comparison = compareCryptoByCategory(selected, analyses); return <div className={card}><h3 className="font-black">Comparacao por categoria</h3><div className="mt-3 grid gap-3 sm:grid-cols-3"><Metric label="Categoria" value={selected.categoryLabel} /><Metric label="Posicao" value={comparison.position === null ? "Dados insuficientes" : `${comparison.position} de ${comparison.total}`} /><Metric label="Media da categoria" value={comparison.averageScore === null ? "Dados insuficientes" : `${comparison.averageScore}/100`} /></div></div>; }
function CryptoAdminSettings({ settings, selectedCategory, onSave }: { settings: CryptoSettings; selectedCategory: CryptoCategory; onSave: (settings: CryptoSettings) => void }) { const [draft, setDraft] = useState({ ...settings.weightsByCategory[selectedCategory] }); useEffect(() => setDraft({ ...settings.weightsByCategory[selectedCategory] }), [settings, selectedCategory]); const sum = Object.values(draft).reduce((a, b) => a + b, 0); return <div className={card}><div className="flex items-center gap-2"><Settings className="h-5 w-5 text-cyan-500" /><h3 className="font-black">Configuracoes do Metodo AlfaTec Cripto</h3></div><label className="mt-4 flex items-center justify-between rounded-2xl bg-slate-50 p-3 text-sm font-bold dark:bg-white/5">Metodo ativo<input type="checkbox" checked={settings.enabled} onChange={(e) => onSave({ ...settings, enabled: e.target.checked })} /></label><p className="mt-4 text-sm font-black">Pesos para {cryptoCategoryLabels[selectedCategory]}</p><div className="mt-3 grid gap-3 sm:grid-cols-2">{(Object.keys(draft) as CryptoPillar[]).map((key) => <label key={key} className="text-xs font-bold text-slate-500">{pillarLabels[key]}<input className="mt-1 h-10 w-full rounded-xl border border-slate-200 bg-white px-3 text-slate-950 dark:border-white/10 dark:bg-slate-950 dark:text-white" type="number" min="0" max="100" value={draft[key]} onChange={(e) => setDraft((current) => ({ ...current, [key]: Number(e.target.value) }))} /></label>)}</div><p className={`mt-3 text-sm font-bold ${sum === 100 ? "text-emerald-500" : "text-red-500"}`}>Soma dos pesos: {sum}%</p><button disabled={sum !== 100} type="button" onClick={() => onSave({ ...settings, weightsByCategory: { ...settings.weightsByCategory, [selectedCategory]: draft } })} className="mt-3 inline-flex items-center gap-2 rounded-2xl bg-cyan-500 px-4 py-3 text-sm font-black text-white disabled:cursor-not-allowed disabled:opacity-50"><Save className="h-4 w-4" />Salvar pesos</button></div>; }
