"use client";
import { AlertTriangle, Bitcoin, ChevronRight } from "lucide-react";
import type { AlfatecCryptoAnalysis } from "@/lib/analysis/alfatec-crypto";
import type { CryptoOpportunityFilterState } from "./CryptoOpportunityFilters";
const usd = new Intl.NumberFormat("pt-BR", { style: "currency", currency: "USD" });
const compact = new Intl.NumberFormat("pt-BR", { notation: "compact", maximumFractionDigits: 2 });
const confidenceRank: Record<string, number> = { Insuficiente: 0, Baixa: 1, Media: 2, Alta: 3 };
export function filterCryptoAnalyses(items: AlfatecCryptoAnalysis[], filters: CryptoOpportunityFilterState) { return items.filter((item) => { const risk = item.pillars.find((pillar) => pillar.key === "risk")?.score; return item.score !== null && item.score >= filters.minScore && (filters.category === "TODAS" || item.category === filters.category) && (item.snapshot.marketCap ?? 0) >= filters.minMarketCap && (item.snapshot.volume24h ?? 0) >= filters.minVolume && (risk ?? 101) <= filters.maxRisk && confidenceRank[item.confidence] >= confidenceRank[filters.minimumConfidence]; }).sort((a, b) => (b.score ?? 0) - (a.score ?? 0)); }
export function CryptoOpportunityTable({ items, onSelect }: { items: AlfatecCryptoAnalysis[]; onSelect: (ticker: string) => void }) { return <div className="overflow-x-auto"><table className="min-w-full text-sm"><thead><tr className="text-left text-slate-500 dark:text-slate-300"><th className="p-3">Ativo</th><th className="p-3">Score</th><th className="p-3">Categoria</th><th className="p-3">Preco</th><th className="p-3">Capitalizacao</th><th className="p-3">Volume 24h</th><th className="p-3">Risco</th><th className="p-3">Confianca</th></tr></thead><tbody>{items.map((item) => <tr key={item.ticker} onClick={() => onSelect(item.ticker)} className="cursor-pointer border-t border-slate-100 hover:bg-slate-50 dark:border-white/10 dark:hover:bg-white/5"><td className="p-3 font-black">{item.ticker}<p className="text-xs font-normal text-slate-500">{item.name}</p></td><td className="p-3 font-black text-cyan-600 dark:text-cyan-300">{item.score}/100</td><td className="p-3">{item.categoryLabel}</td><td className="p-3">{item.snapshot.price === null ? "Dado indisponivel" : usd.format(item.snapshot.price)}</td><td className="p-3">{item.snapshot.marketCap === null ? "Dado indisponivel" : `US$ ${compact.format(item.snapshot.marketCap)}`}</td><td className="p-3">{item.snapshot.volume24h === null ? "Dado indisponivel" : `US$ ${compact.format(item.snapshot.volume24h)}`}</td><td className="p-3">{item.pillars.find((pillar) => pillar.key === "risk")?.score ?? "--"}/100</td><td className="p-3">{item.confidence === "Media" ? "Media" : item.confidence}</td></tr>)}</tbody></table>{items.length === 0 && <p className="p-4 text-sm text-slate-500">Nenhum criptoativo com dados reais atende aos filtros.</p>}</div>; }
export function CryptoComparison({ a, b }: { a: AlfatecCryptoAnalysis; b: AlfatecCryptoAnalysis }) { const sameCategory = a.category === b.category; const rows = ["fundamentals", "network", "tokenomics", "security", "market", "development", "onChainValuation", "risk"].map((key) => { const pa = a.pillars.find((item) => item.key === key); const pb = b.pillars.find((item) => item.key === key); return [pa?.label ?? key, pa?.score === null || pa?.score === undefined ? "Dado indisponivel" : `${pa.score}/100`, pb?.score === null || pb?.score === undefined ? "Dado indisponivel" : `${pb.score}/100`]; }); return <div className="mt-5 rounded-3xl border border-slate-200 p-4 dark:border-white/10"><h4 className="font-black">Comparacao pelo Metodo AlfaTec Cripto</h4>{!sameCategory && <p className="mt-3 flex gap-2 rounded-2xl bg-amber-500/10 p-3 text-sm font-semibold text-amber-700 dark:text-amber-300"><AlertTriangle className="h-5 w-5" />Os ativos possuem funcoes e estruturas diferentes. Interprete a comparacao com cautela.</p>}<div className="mt-4 overflow-hidden rounded-2xl border border-slate-200 text-sm dark:border-white/10"><div className="grid grid-cols-3 bg-slate-50 p-3 font-bold dark:bg-white/5"><span>Criterio</span><span>{a.ticker}</span><span>{b.ticker}</span></div><Row label="Score AlfaTec Cripto" a={a.score === null ? "Dados insuficientes" : `${a.score}/100`} b={b.score === null ? "Dados insuficientes" : `${b.score}/100`} /><Row label="Categoria" a={a.categoryLabel} b={b.categoryLabel} />{rows.map((row) => <Row key={row[0]} label={row[0]} a={row[1]} b={row[2]} />)}<Row label="Confianca" a={a.confidence} b={b.confidence} /></div></div>; }
function Row({ label, a, b }: { label: string; a: string; b: string }) { return <div className="grid grid-cols-3 border-t border-slate-100 p-3 dark:border-white/10"><span className="text-slate-500 dark:text-slate-300">{label}</span><strong>{a}</strong><strong>{b}</strong></div>; }
export function CryptoMiniSummary({ analysis, onOpen }: { analysis: AlfatecCryptoAnalysis | null; onOpen: () => void }) { if (!analysis) return null; return <div className="mt-5 rounded-3xl border border-cyan-400/30 bg-cyan-500/10 p-4"><div className="flex items-start gap-3"><Bitcoin className="h-6 w-6 text-amber-500" /><div className="flex-1"><h4 className="font-black">Metodo AlfaTec Cripto</h4><p className="mt-1 text-sm text-slate-600 dark:text-slate-300">Score {analysis.score === null ? "indisponivel" : `${analysis.score}/100`} - {analysis.classification} - Confianca {analysis.confidence}.</p><button type="button" onClick={onOpen} className="mt-3 inline-flex items-center gap-1 text-sm font-black text-cyan-700 dark:text-cyan-300">Ver analise completa <ChevronRight className="h-4 w-4" /></button></div></div></div>; }
